wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/forest-light.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/forest-light.jpg
    fit_mode = cover
}

splash = false
